jwt:
  secret: 984hg493grt67m6thr0429uruj2309yh9gjhc763fe87t3f89723gf
  lifetime: 30d
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/romsDB
    username: postgres
    password: Vadim2005ogoniyk2005
    driver-class-name: org.postgresql.Driver
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          ddl-auto: update
